/**
 * Comprehensive Report: Superhuman Event ID Format Analysis
 */

import { connectToSuperhuman, disconnect } from "./src/superhuman-api";

async function main() {
  console.log("=".repeat(70));
  console.log("SUPERHUMAN EVENT ID FORMAT ANALYSIS REPORT");
  console.log("=".repeat(70));
  console.log();

  const conn = await connectToSuperhuman(9333);
  if (!conn) {
    console.error("Failed to connect to Superhuman");
    process.exit(1);
  }

  const { Runtime } = conn;

  // 1. Get team ID for reference
  console.log("1. TEAM ID REFERENCE");
  console.log("-".repeat(40));

  const teamIdResult = await Runtime.evaluate({
    expression: `
      (() => {
        const ga = window.GoogleAccount;
        return ga?.accountStore?.state?.account?.settings?._cache?.pseudoTeamId || 'not found';
      })()
    `,
    returnByValue: true
  });

  const teamId = teamIdResult.result?.value || "not found";
  console.log(`Team ID: ${teamId}`);
  if (teamId !== "not found") {
    const suffix = teamId.replace("team_", "");
    console.log(`  Prefix: team_`);
    console.log(`  Suffix: ${suffix}`);
    console.log(`  Suffix length: ${suffix.length}`);
    console.log();

    // Analyze character composition
    const hasUpper = /[A-Z]/.test(suffix);
    const hasLower = /[a-z]/.test(suffix);
    const hasDigit = /[0-9]/.test(suffix);
    console.log(`  Has uppercase: ${hasUpper}`);
    console.log(`  Has lowercase: ${hasLower}`);
    console.log(`  Has digits: ${hasDigit}`);
    console.log(`  Character set: Base62 (A-Za-z0-9)`);
  }

  // 2. Event ID format analysis
  console.log();
  console.log("2. EVENT ID FORMAT (EXPECTED)");
  console.log("-".repeat(40));
  console.log("Based on API error 'invalid-question-event-id' and pattern analysis:");
  console.log();
  console.log("  Format: event_ + <suffix>");
  console.log("  Expected suffix: 17-18 base62 characters");
  console.log("  Example from code: event_11VNPdc4sKP2pEaKSz");
  console.log();
  console.log("  CRITICAL: Event IDs appear to be SERVER-VALIDATED");
  console.log("  - Random generation does NOT work (returns 400 invalid-question-event-id)");
  console.log("  - IDs may contain encoded data (timestamp, user, signature)");
  console.log("  - IDs may be pre-generated by server and cached client-side");

  // 3. Session ID format
  console.log();
  console.log("3. SESSION ID FORMAT");
  console.log("-".repeat(40));
  console.log("  Format: UUID v4 (standard)");
  console.log("  Example: xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx");
  console.log("  Length: 36 characters");
  console.log("  Can be generated with: crypto.randomUUID()");

  // 4. API Endpoint
  console.log();
  console.log("4. API ENDPOINT");
  console.log("-".repeat(40));
  console.log("  URL: https://mail.superhuman.com/~backend/v3/ai.askAIProxy");
  console.log("  Method: POST");
  console.log("  Auth: Bearer token (idToken from credential)");
  console.log();
  console.log("  Request Body Fields:");
  console.log("    - session_id: UUID v4");
  console.log("    - question_event_id: event_<suffix> (SERVER VALIDATED)");
  console.log("    - query: string");
  console.log("    - chat_history: array");
  console.log("    - user: { provider_id, email, name, company, position }");
  console.log("    - local_datetime: ISO datetime");
  console.log("    - current_thread_id: string");
  console.log("    - current_thread_messages: array");

  // 5. Backend methods found
  console.log();
  console.log("5. BACKEND AI METHODS");
  console.log("-".repeat(40));
  console.log("Found in GoogleAccount.backend:");
  console.log("  - aiCompose (no event ID needed)");
  console.log("  - aiComposeEdit (questionEventId parameter)");
  console.log("  - aiComposeAgentic (questionEventId parameter)");
  console.log("  - getAICalendarDetails");
  console.log("  - semanticSearch (questionEventId parameter)");

  // 6. Recommendations
  console.log();
  console.log("6. RECOMMENDATIONS");
  console.log("-".repeat(40));
  console.log();
  console.log("  Option A: Intercept Real IDs");
  console.log("    - Use CDP fetch interception when user triggers Ask AI");
  console.log("    - Capture the question_event_id from actual requests");
  console.log("    - Use those IDs for subsequent API calls");
  console.log();
  console.log("  Option B: Call Backend Methods Directly");
  console.log("    - Use GoogleAccount.backend.aiCompose() which doesn't need event ID");
  console.log("    - Use Runtime.evaluate to call the method through CDP");
  console.log();
  console.log("  Option C: Find Pre-generated IDs");
  console.log("    - Event IDs may be pre-generated and cached");
  console.log("    - Search localStorage/sessionStorage/IndexedDB for cached IDs");
  console.log();

  // 7. Try Option B - call aiCompose directly
  console.log("7. TESTING OPTION B: DIRECT BACKEND CALL");
  console.log("-".repeat(40));

  const testResult = await Runtime.evaluate({
    expression: `
      (async () => {
        try {
          const ga = window.GoogleAccount;
          const backend = ga?.backend;

          if (!backend?.aiCompose) {
            return { error: 'aiCompose method not found' };
          }

          // Get a sample thread
          const threadId = '19b4d2a9561472a1';

          // Try calling aiCompose (it doesn't need event ID)
          const result = await backend.aiCompose({
            instructions: 'Write a brief thank you response',
            draftAction: 'compose',
            threadContent: 'Sample thread content for testing',
            subject: 'Re: Test',
            to: [],
            cc: [],
            bcc: [],
            threadId: threadId,
            lastMessageId: null,
            draftContent: '',
            draftContentType: 'text'
          });

          // Result is a stream reader function
          if (typeof result === 'function') {
            const streamResult = await result();
            return {
              success: true,
              type: 'stream',
              hasReader: true,
              sample: JSON.stringify(streamResult).substring(0, 200)
            };
          }

          return { success: true, result: JSON.stringify(result).substring(0, 200) };
        } catch (e) {
          return { error: e.message, stack: e.stack?.substring(0, 300) };
        }
      })()
    `,
    returnByValue: true,
    awaitPromise: true,
    timeout: 30000
  });

  console.log();
  console.log("Test result:", JSON.stringify(testResult.result?.value, null, 2));

  await disconnect(conn);

  // Summary
  console.log();
  console.log("=".repeat(70));
  console.log("SUMMARY");
  console.log("=".repeat(70));
  console.log();
  console.log("The question_event_id is SERVER-VALIDATED and cannot be randomly");
  console.log("generated. The backend likely uses this ID for:");
  console.log("  1. Rate limiting / abuse prevention");
  console.log("  2. Analytics tracking");
  console.log("  3. Session correlation");
  console.log();
  console.log("To use the Ask AI API, you need to either:");
  console.log("  A. Intercept real event IDs from the UI");
  console.log("  B. Use backend methods that don't require event IDs (aiCompose)");
  console.log("  C. Find where event IDs are pre-generated/cached");
  console.log();
}

main().catch(console.error);
